// DO NOT EDIT MANUALLY - Auto-generated by `make collections-sync`
// Generated file: frontend/src/types/PBCollections.d.ts

/**
 * PocketBase collection metadata present on all records
 */
interface PBBaseRecord {
  collectionId: string;
  collectionName: string;
}

/**
snapshot = {
  "createRule": "organization.owner.id = @request.auth.id || (@request.auth.id != \"\" && organization.memberships_via_organization.user.id ?= @request.auth.id && organization.memberships_via_organization.role ?= \"admin\")",
  "deleteRule": "(organization.owner.id = @request.auth.id) || (@request.auth.id != \"\" && organization.memberships_via_organization.user.id ?= @request.auth.id && organization.memberships_via_organization.role ?= \"admin\" && role != \"owner\") || (user.id = @request.auth.id && role != \"owner\")",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "relation_membership_user",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "user",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": true,
      "collectionId": "pbc_organizations",
      "hidden": false,
      "id": "relation_membership_org",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "organization",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "relation"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text_membership_role",
      "max": 20,
      "min": 1,
      "name": "role",
      "pattern": "",
      "presentable": true,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "relation_membership_invited_by",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "invited_by",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text_membership_invite_email",
      "max": 255,
      "min": 0,
      "name": "invite_email",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "id": "pbc_memberships",
  "indexes": [
    "CREATE UNIQUE INDEX idx_membership_user_org ON memberships (user, organization) WHERE user != ''"
  ],
  "listRule": "user.id = @request.auth.id || organization.owner.id = @request.auth.id || (@request.auth.id != \"\" && organization.memberships_via_organization.user.id ?= @request.auth.id)",
  "name": "memberships",
  "system": false,
  "type": "base",
  "updateRule": "organization.owner.id = @request.auth.id",
  "viewRule": "user.id = @request.auth.id || organization.owner.id = @request.auth.id || (@request.auth.id != \"\" && organization.memberships_via_organization.user.id ?= @request.auth.id)"
}
 */
export interface MembershipsRecord extends PBBaseRecord {
  id: string;
  user?: string;
  organization: string;
  role: string;
  invited_by?: string;
  invite_email?: string;
  created?: string;
  updated?: string;
  collectionName: 'memberships';
}

/**
snapshot = {
  "createRule": "@request.auth.id != \"\"",
  "deleteRule": "owner.id = @request.auth.id",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text_org_name",
      "max": 100,
      "min": 1,
      "name": "name",
      "pattern": "",
      "presentable": true,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text_org_description",
      "max": 500,
      "min": 0,
      "name": "description",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "relation_org_owner",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "owner",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "relation"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "id": "pbc_organizations",
  "indexes": [],
  "listRule": "owner.id = @request.auth.id || @request.auth.id ?= memberships_via_organization.user.id",
  "name": "organizations",
  "system": false,
  "type": "base",
  "updateRule": "owner.id = @request.auth.id",
  "viewRule": "owner.id = @request.auth.id || @request.auth.id ?= memberships_via_organization.user.id"
}
 */
export interface OrganizationsRecord extends PBBaseRecord {
  id: string;
  name: string;
  description?: string;
  owner: string;
  created?: string;
  updated?: string;
  collectionName: 'organizations';
}

/**
snapshot = {
  "createRule": "user.id = @request.auth.id",
  "deleteRule": null,
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "relation2375276105",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "user",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text1232909984",
      "max": 0,
      "min": 0,
      "name": "feedback_type",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text3065852031",
      "max": 0,
      "min": 0,
      "name": "message",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "bool1517216936",
      "name": "reply_desired",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text1326724116",
      "max": 0,
      "min": 0,
      "name": "metadata",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "id": "pbc_3683687721",
  "indexes": [],
  "listRule": "user.id = @request.auth.id",
  "name": "user_feedback",
  "system": false,
  "type": "base",
  "updateRule": null,
  "viewRule": "user.id = @request.auth.id"
}
 */
export interface UserFeedbackRecord extends PBBaseRecord {
  id: string;
  user?: string;
  feedback_type: string;
  message: string;
  reply_desired?: boolean;
  metadata?: string;
  created?: string;
  updated?: string;
  collectionName: 'user_feedback';
}

/**
snapshot = {
  "authAlert": {
    "emailTemplate": {
      "body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
      "subject": "Login from a new location"
    },
    "enabled": true
  },
  "authRule": "",
  "authToken": {
    "duration": 604800
  },
  "confirmEmailChangeTemplate": {
    "body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
    "subject": "Confirm your {APP_NAME} new email address"
  },
  "createRule": "",
  "deleteRule": "id = @request.auth.id",
  "emailChangeToken": {
    "duration": 1800
  },
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cost": 0,
      "hidden": true,
      "id": "password901924565",
      "max": 0,
      "min": 8,
      "name": "password",
      "pattern": "",
      "presentable": false,
      "required": true,
      "system": true,
      "type": "password"
    },
    {
      "autogeneratePattern": "[a-zA-Z0-9]{50}",
      "hidden": true,
      "id": "text2504183744",
      "max": 60,
      "min": 30,
      "name": "tokenKey",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "exceptDomains": null,
      "hidden": false,
      "id": "email3885137012",
      "name": "email",
      "onlyDomains": null,
      "presentable": false,
      "required": true,
      "system": true,
      "type": "email"
    },
    {
      "hidden": false,
      "id": "bool1547992806",
      "name": "emailVisibility",
      "presentable": false,
      "required": false,
      "system": true,
      "type": "bool"
    },
    {
      "hidden": false,
      "id": "bool256245529",
      "name": "verified",
      "presentable": false,
      "required": false,
      "system": true,
      "type": "bool"
    },
    {
      "autogeneratePattern": "",
      "hidden": false,
      "id": "text1579384326",
      "max": 255,
      "min": 0,
      "name": "name",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "file376926767",
      "maxSelect": 1,
      "maxSize": 0,
      "mimeTypes": [
        "image/jpeg",
        "image/png",
        "image/svg+xml",
        "image/gif",
        "image/webp"
      ],
      "name": "avatar",
      "presentable": false,
      "protected": false,
      "required": false,
      "system": false,
      "thumbs": null,
      "type": "file"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "fileToken": {
    "duration": 180
  },
  "id": "_pb_users_auth_",
  "indexes": [
    "CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)",
    "CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''"
  ],
  "listRule": "id = @request.auth.id",
  "manageRule": null,
  "mfa": {
    "duration": 1800,
    "enabled": false,
    "rule": ""
  },
  "name": "users",
  "oauth2": {
    "enabled": false,
    "mappedFields": {
      "avatarURL": "avatar",
      "id": "",
      "name": "name",
      "username": ""
    }
  },
  "otp": {
    "duration": 180,
    "emailTemplate": {
      "body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
      "subject": "OTP for {APP_NAME}"
    },
    "enabled": false,
    "length": 8
  },
  "passwordAuth": {
    "enabled": true,
    "identityFields": [
      "email"
    ]
  },
  "passwordResetToken": {
    "duration": 1800
  },
  "resetPasswordTemplate": {
    "body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
    "subject": "Reset your {APP_NAME} password"
  },
  "system": false,
  "type": "auth",
  "updateRule": "id = @request.auth.id",
  "verificationTemplate": {
    "body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
    "subject": "Verify your {APP_NAME} email"
  },
  "verificationToken": {
    "duration": 259200
  },
  "viewRule": "id = @request.auth.id"
}
 */
export interface UsersRecord extends PBBaseRecord {
  id: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: string;
  created?: string;
  updated?: string;
  collectionName: 'users';
}

export type CollectionRecords = {
  memberships: MembershipsRecord;
  organizations: OrganizationsRecord;
  user_feedback: UserFeedbackRecord;
  users: UsersRecord;
};
