// Auto-generated by tasks/generate-pb-types.mjs
// Run `npm run generate-pb-types` to regenerate. DO NOT EDIT MANUALLY.
// Generated file: PBCollections.d.ts

/**
 * PocketBase system fields present on all records
 */
interface PBBaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface FeedbackActionsRecord extends PBBaseRecord {
  id: string;
  user_feedback: string;
  action: string;
  collectionName: 'feedback_actions';
}

export interface MembershipsRecord extends PBBaseRecord {
  id: string;
  user?: string;
  organization: string;
  role: string;
  invited_by?: string;
  invite_email?: string;
  collectionName: 'memberships';
}

export interface OrganizationsRecord extends PBBaseRecord {
  id: string;
  name: string;
  description?: string;
  owner: string;
  collectionName: 'organizations';
}

export interface UserFeedbackRecord extends PBBaseRecord {
  id: string;
  user?: string;
  feedback_type: string;
  message: string;
  reply_desired?: boolean;
  metadata?: string;
  feedback_actions?: string[];
  collectionName: 'user_feedback';
}

export interface UserPreferencesRecord extends PBBaseRecord {
  id: string;
  user: string;
  alert_preferred_method: string;
  alert_phone_number?: string;
  alert_phone_number_subscribed?: boolean;
  collectionName: 'user_preferences';
}

export type CollectionRecords = {
  feedback_actions: FeedbackActionsRecord;
  memberships: MembershipsRecord;
  organizations: OrganizationsRecord;
  user_feedback: UserFeedbackRecord;
  user_preferences: UserPreferencesRecord;
};
